### ISSUE TITLE
feat (profiles): tracker

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#15]
As per documentation here: https://docs.freelabz.com/in-depth/concepts/profiles-wip

- [ ] https://github.com/freelabz/secator/issues/67
- [ ] https://github.com/freelabz/secator/issues/172
- [ ] https://github.com/freelabz/secator/issues/337
- [x] https://github.com/freelabz/secator/issues/338
