### ISSUE TITLE
feat: uniformize vulnerability output with nuclei's

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#328]
**nuclei:**
```
[redis-info] [javascript] [info] localhost:6379 ["used_cpu_user:152.982133","connected_clients:1","connected_slaves:0","used_memory_human:1019.02K","role:master","redis_version:7.0.15","process_id:1011","used_cpu_sys:189.236039"]
[redis-default-logins] [javascript] [high] localhost:6379 [passwords="admin"]
```

**secator:**
```
🚨 [redis-info 🡕] [info] localhost:6379 [js,redis,network] [redis_version:7.0.15,process_id:1011,used_cpu_sys:189.236039,used_cpu_user:154.148712,connected_clients:2,connected_slaves:0,used_memory_human:1.03M,role:master]
🚨 [redis-default-logins 🡕] [high] localhost:6379 [js,redis,default-login,network] [passwords: admin]
```

**Tasks:**
- [ ] Uniformize CLI colors with `nuclei`'s
- [ ] Rework `tasks/nuclei.py:nuclei.extra_data_extractor`
- [ ] Rework `output_types/vulnerability.py` (add `type`, rework `extra_data`)
