### ISSUE TITLE
feat(error handling): tracker

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#351]
- [x] https://github.com/freelabz/secator/issues/268
- [x] https://github.com/freelabz/secator/issues/269
- [x] https://github.com/freelabz/secator/issues/354
- [x] https://github.com/freelabz/secator/issues/355
- [x] https://github.com/freelabz/secator/issues/356
- [x] https://github.com/freelabz/secator/issues/357
- [x] https://github.com/freelabz/secator/issues/358
