### ISSUE TITLE
install: enhancements tracker

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#494]
- [ ] https://github.com/freelabz/secator/issues/416
- [ ] https://github.com/freelabz/secator/issues/414
- [ ] https://github.com/freelabz/secator/issues/312
- [ ] https://github.com/freelabz/secator/issues/305
- [ ] https://github.com/freelabz/secator/issues/294
- [ ] https://github.com/freelabz/secator/issues/149
- [ ] https://github.com/freelabz/secator/issues/281
- [ ] https://github.com/freelabz/secator/issues/248
